package com.example.espainour.model;

public enum EstatusLegal {
    RECIEN_LLEGADO,
    SOLICITANTE_DE_ASILO,
    REFUGIADO_RECONOCIDO,
    PROTECCION_SUBSIDIARIA,
    APATRIDA,
    RESIDENCIA_TEMPORAL,
    RESIDENCIA_PERMANENTE,
    SIN_DOCUMENTACION,
    OTRO
}
